version: "3.8"

x-common-variables: &common-variables
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_SERVER: $POSTGRES_SERVER
  DB_PORT: $DB_PORT
  SECRET_KEY: $SECRET_KEY
  ALLOWED_HOSTS: $ALLOWED_HOSTS
  BOT_TOKEN: $BOT_TOKEN
  SECRET_KEY_YOOKASSA: $SECRET_KEY_YOOKASSA
  SHOP_ID_YOOKASSA: $SHOP_ID_YOOKASSA
  REDIRECT_URL: $REDIRECT_URL

services:
  web:
    image: gmoroz/bottec_test:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      *common-variables
    entrypoint: ["sh", "entrypoint.sh"]
    ports:
      - 80:80
    volumes:
      - staticdata:/usr/src/app/static_files
    depends_on:
      db:
        condition: service_healthy

  bot:
    image: gmoroz/bottec_test:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: ["python", "/code/start_bot.py"]
    environment:
      *common-variables
    depends_on:
      - web

  db:
    image: postgres:latest
    environment:
      *common-variables
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  postgres_data:
  staticdata:
